### PR TITLE
Dynamically call the handler instance

### PR DESCRIPTION
**Pull request by agungsugiarto**

### CODE REVIEW

**Comment by MGatner** [comment]
@agungsugiarto I liked this solution, maybe with a guard for actual callable methods. Is there a reason you closed it?

**Comment by agungsugiarto** [comment]
@MGatner  close because already implement. https://github.com/lonnieezell/codigniter-shield/blob/3acb1761ceb9b385408ec3265c084c8c2049b3bd/src/Auth.php#L137-L146

**Comment by MGatner** [comment]
Oh! Ha I missed that, sorry. Glad to see it made it.

**Comment by agungsugiarto** [comment]
Take a look my adaption @MGatner, im just playing with authentication.
https://github.com/agungsugiarto/codeigniter4-authentication.git

**Comment by MGatner** [comment]
I will check it out later this week, thanks for sharing!

**Pull request closed without merging**
